"""Taint inheritance store for files generated by agent/tool outputs."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from ..models import sha256_text, utc_now
from .registry import RegistryRule, TwoLayerRegistry


@dataclass(slots=True)
class TaintRecord:
    path: str
    source_ids: list[str]
    trust: str
    confidentiality: str
    reason: str
    written_at: str = field(default_factory=utc_now)
    content_hash: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


class TaintStore:
    def __init__(self, registry: TwoLayerRegistry | None = None) -> None:
        self.registry = registry or TwoLayerRegistry()
        self.records: dict[str, TaintRecord] = {}

    def record_write(self, path: str, content: str, source_ids: list[str], trust: str = "tainted", confidentiality: str = "LOW", reason: str = "agent_generated_from_untrusted_source") -> TaintRecord:
        rec = TaintRecord(path=path, source_ids=source_ids, trust=trust, confidentiality=confidentiality, reason=reason, content_hash=sha256_text(content))
        self.records[self._norm(path)] = rec
        self.registry.add_user_rule(RegistryRule(self._norm(path), confidentiality=confidentiality, trust=trust, risk="high" if trust in {"tainted", "untrusted", "tool_untrusted"} else "medium", capabilities=["taint_inherited"], metadata={"source_ids": source_ids, "reason": reason}))
        return rec

    def read_context(self, path: str) -> dict[str, Any]:
        norm = self._norm(path)
        base = self.registry.classify_path(norm)
        rec = self.records.get(norm)
        if not rec:
            return {"path": norm, "tainted": False, "classification": base}
        return {"path": norm, "tainted": True, "source_ids": rec.source_ids, "trust": rec.trust, "confidentiality": rec.confidentiality, "reason": rec.reason, "classification": base}

    @staticmethod
    def _norm(path: str) -> str:
        return path.replace("\\", "/").lstrip("/")
